export const STORE_PROJECT_ID = "STORE_PROJECT_ID";
export const STORE_USERS = "STORE_USERS";
export const STORE_PROJECTS = "STORE_PROJECTS";
export const STORE_OWNER_ID = "STORE_OWNER_ID";
export const STORE_USER_TO_USERS = "STORE_USER_TO_USERS";
export const STORE_CEP = "STORE_CEP";